### ISSUE TITLE
no DELAY

### ISSUE THREAD

**Issue by Nibot1** [Seytonic/malduino#14]
My Malduino Elite doesnt make an delay of the duration wich is set in the Duckyscript.

**Comment by Nibot1** [comment]
I fixed the issue for me.
I changed the “#define buffersize 256” to “#define buffersize 128”

**Comment by kplaczek** [comment]
This. I don't know why it is like this and why there is no response cron creator. But thanks to @Nibot1 I have wasted just a little bit of time figuring why delay is not working and malduino is useless without it. Thank you.
