### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by dutchpatriot** [Seytonic/malduino#16]
Never mind...
 
Grts and great work!

**Comment by drowlands** [comment]
Spam?

**Comment by dutchpatriot** [comment]
No I thought to have a smart idea with having 2 more options with a 4dip switch...

But after some more thinking it just stayed the same... Haha, well it did gave me the idea, because with the solution I thought that was no solution and stayed the same, I came to the idea to connect a few voltage dividers to a multi switch on a analog channel so you can multiply your dipswitch count by the number of dividers...

Sry for removing the issue...
