### ISSUE TITLE
Digispark support

### ISSUE THREAD

**Issue by albznw** [Seytonic/malduino#18]
Thought it would be nice with support for the Digispark based on ATTINY85.
Is it possible?

Picture of the board: ![Digispark](https://img.banggood.com/thumb/water/2014/xiemeijuan/10/SKU172392/SKU172392d.jpg "Digispark")

Also, sorry if ideas or stuff like this is not meant to be proposed as issues.
I'm new to this.

**Comment by fionafibration** [comment]
This is a repo for the Malduino, if you're looking for something for the Digispark, there is a converter [here](https://github.com/CedArctic/digiQuack)

**Comment by Soneji** [comment]
Hey @albznw @Fiona1729 , sorry for spamming in this thread, but I'd love to know if either of you knew what the actual board/chip the malduino (lite) is based on?

Thanks so much

**Comment by albznw** [comment]
Hey @Soneji! No, not really!
